### ISSUE TITLE
赞。不过前端构建物不完整，希望能更新

### ISSUE THREAD

**Issue by andy3560531** [metaxk-company/free-mes#1]
1、前端构建物不完整，希望能更新，不过幸好有官方演示环境，nginx配置所有静态资源转发到官方演示环境，可以运行，不过记得修改index.html中引用的主js文件名，以及该js里面的后台调用地址。
2、centos系统部署时，挂载timezone文件会失败，因为centos里面/etc/timezone是个目录，在该目录下创建timezone文件并写入时区信息，然后修改compose编排文件timezone挂载路径即可。
3、第一次运行，db初始化比较久，后台服务启动后还没初始完，后台服务会报错数据库链接不上，等一会就可以了。

**Comment by zhangkuansky** [comment]
1. 参照官网的页面，修改index.html里js的文件名
2. nginx.conf里添加下面的配置(域名转发）:

	location /assets/ {
	
		proxy_pass https://mesv2.cloudmes.io;
		proxy_ssl_server_name on;
		proxy_ssl_session_reuse off;
	
	    # 解压html, js文件
		proxy_set_header Accept-Encoding "";
		
		# 替换api的公网地址
		sub_filter 'https://mesv2-api.cloudmes.io' 'http://xxx:48080';
		sub_filter_types *;
		sub_filter_once off;
		}
